pubsub:
  subscription:
    event: events-develop-subscription

datastore:
  kind:
    event: TestEvent
    decision-history: TestDecisionHistory

storage:
  bucket_name: rtdpublic
  folder_namne: Rules/